name: on_dock
description: A smart app for truck drivers and people on the move

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0  # For beautiful fonts
  animated_text_kit: ^4.2.2  # For cool text animations
  flutter_spinkit: ^5.2.0  # For loading animations

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # Add your assets here
  assets:
    - assets/images/OnDock.png
    - assets/images/Vector.png
    - assets/images/Vector1.png
    - assets/icons/OnDock Icon_dock light monitor.png
    - assets/icons/OnDock Icon_message.png
    - assets/icons/OnDock Icon_clock.png
    - assets/icons/OnDock Icon_map.png



  
  
  # Add custom fonts (we'll use Google Fonts for now)
  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/PlusJakartaSans-Light.ttf
          weight: 300
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSans-ExtraBold.ttf
          weight: 800
    
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-ExtraLightItalic.ttf
          weight: 200
        - asset: assets/fonts/PlusJakartaSans-LightItalic.ttf
          weight: 300
        - asset: assets/fonts/PlusJakartaSans-Italic.ttf
          weight: 400
        - asset: assets/fonts/PlusJakartaSans-MediumItalic.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans-SemiBoldItalic.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSans-BoldItalic.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSans-ExtraBoldItalic.ttf
          weight: 800
